#%RAML 1.0
title: ACME Banking API
version: 1.0
baseUri: http://www.placeholder.com/api/v1/

documentation:
  - title: ACME Banking API
    content: |
      This is the full API for instructors to use as a sample solution for the API Design and Architecture class.

mediaType: application/json

/customers:
  description: The full collection of all users with accounts at the bank
  get:
    description: Retrieve a list of all the bank's customers
    responses:
      200:
        body:
          example: |
            [
              {
                "user_id": "1234",
                "user_name": "Nora Charles",
                "description": "This is the ACME account of Nora Charles",
                "dob": "01/01/1970"
              },
              {
                "user_id": "4321",
                "user_name": "Ray Charles",
                "description": "This is the ACME account of Ray Charles",
                "dob": "01/01/1970"
              }
            ]
      404:
        body:
          example: |
            {
              "http.statuscode" : 404,
              "message" : "Resource not found."
            }
  post:
    description: Adds a new user to the bank's customer listing
    body:
      example: |
        {
          "user_name": "John Doe",
          "description": "This is the ACME account of John Doe",
          "dob": "01/01/1970"
        }
    responses:
      201:
        body:
          example: |
            {
              "http.statuscode" : 201,
              "message" : "Resource created."
            }
  /{customer_id}:
    get:
      description: Retrieve a specific customer
      responses:
        200:
          body:
            example: |
              {
                "user_id": "4321",
                "user_name": "Ray Charles",
                "description": "This is the ACME account of Ray Charles",
                "dob": "01/01/1970"
              }
        404:
          body:
            example: |
              {
                "http.statuscode" : 404,
                "message" : "Resource not found."
              }
    delete:
      description: Delete a specific customer
      responses:
        200:
          body:
            example: |
              {
                "http.statuscode" : 200,
                "message" : "Operation completed successfully."
              }
    put:
      description: Update or create a specific customer
      body:
        example: |
          {
            "user_id": "9999",
            "user_name": "John Doe",
            "description": "This is the ACME account of John Doe",
            "dob": "01/01/1970"
          }
      responses:
        200:
          body:
            example: |
              {
                "http.statuscode" : 200,
                "message" : "Operation completed successfully."
              }
        201:
          body:
            example: |
              {
                "http.statuscode" : 201,
                "message" : "Resource created."
              }
    /accounts:
      get:
        description: Retrieve a list of accounts belonging to a specific customer
        responses:
          200:
            body:
              example: |
                uses:
                  key:
                [
                  {
                    "account_id" : "a2esd212343123",
                    "account_type" : "checking",
                    "customer_id" : "1234",
                    "balance": 1252.00
                  },
                  {
                    "account_id" : "a3esd212343123",
                    "account_type" : "savings",
                    "customer_id" : "4321",
                    "balance": 13000.00
                  }
                ]
      post:
        description: Add a new bank account to a specific customer
        body:
          example: |
            {
              "account_type" : "checking",
              "customer_id" : "9999",
              "balance": 0.00
            }
        responses:
          201:
            body:
              example: |
                {
                  "http.statuscode" : 201,
                  "message" : "Resource created."
                }
      /{account_id}:
        get:
          description: Retrieve a bank account belonging to a specific customer
          responses:
            200:
              body:
                example: |
                  {
                    "account_id" : "a3esd212343123",
                    "account_type" : "checking",
                    "customer_id" : "1234",
                    "balance": 113300.00
                  }
            404:
              body:
                example: |
                  {
                    "http.statuscode" : 404,
                    "message" : "Resource not found."
                  }
        put:
          description: Update a bank account belonging to a specific customer
          responses:
            200:
              body:
                example: |
                  {
                    "http.statuscode" : 200,
                    "message" : "Operation completed successfully."
                  }
            201:
              body:
                example: |
                  {
                    "http.statuscode" : 201,
                    "message" : "Resource created."
                  }
        delete:
          description: Close a bank account belonging to a specific customer
          responses:
            200:
              body:
                example: |
                  {
                    "http.statuscode" : 200,
                    "message" : "Operation completed successfully."
                  }
        /outgoingTransfers:
          get:
            description: Retrieve a list of transfers that have been sent from a customer's bank account
            responses:
              200:
                body:
                  example: |
                    [
                      {
                        "sourceAccount_id" : "3523djfg329548",
                        "targetAccount_id" : "a2esd212343123",
                        "amount": 27.00,
                        "description": "My share of last night's dinner"
                      },
                      {
                        "sourceAccount_id" : "3523djfg123123",
                        "targetAccount_id" : "a2esd212343123",
                        "ammount": 1324.00,
                        "description": "rent June 2015"
                      }
                    ]
          post:
            description: Create a new outgoing transaction
            responses:
              201:
                body:
                  example: |
                    {
                      "http.statuscode" : 201,
                      "message" : "Resource created."
                    }
          /{transfer_id}:
            get:
              description: Retrieve a specific transfer that has been sent from a customer's bank account
              responses:
                200:
                  body:
                    example: |
                      {
                        "sourceAccount_id" : "a2esd212343123",
                        "targetAccount_id" : "3523djfg329548",
                        "amount": 1000.00,
                        "description": "This is the description of a particular transaction that you provided at creation."
                      }
                404:
                  body:
                    example: |
                      {
                        "http.statuscode" : 404,
                        "message" : "Resource not found."
                      }
        /incomingTransfers:
          get:
            description: Retrieve a list of transfers that have been sent to a customer's bank account
            responses:
              200:
                body:
                  example: |
                    [
                      {
                        "sourceAccount_id" : "3523djfg329548",
                        "targetAccount_id" : "a2esd212343123",
                        "amount": 27.00,
                        "description": "My share of last night's dinner"
                      },
                      {
                        "sourceAccount_id" : "3523djfg123123",
                        "targetAccount_id" : "a2esd212343123",
                        "ammount": 1324.00,
                        "description": "rent June 2015"
                      }
                    ]
          /{transfer_id}:
            get:
              description: Retrieve a specific transfer that has been sent to a customer's bank account
              responses:
                200:
                  body:
                    example: |
                      {
                        "sourceAccount_id" : "a2esd212343123",
                        "targetAccount_id" : "3523djfg329548",
                        "amount": 1000.00,
                        "description": "This is the description of a particular transaction that you provided at creation."
                      }
                404:
                  body:
                    example: |
                      {
                        "http.statuscode" : 404,
                        "message" : "Resource not found."
                      }
/transfers:
 get:
   description: Retrieve a full list of transfers
   responses:
     200:
       body:
         example: |
           [
             {
               "sourceAccount_id" : "3523djfg329548",
               "targetAccount_id" : "a2esd212343123",
               "amount": 27.00,
               "description": "My share of last night's dinner"
             },
             {
               "sourceAccount_id" : "3523djfg123123",
               "targetAccount_id" : "a2esd212343123",
               "ammount": 1324.00,
               "description": "rent June 2015"
             }
           ]
